#!/usr/bin/env python3
"""Generate the directory indexes ``reports/README.md``, ``scripts/README.md`` and ``docs/README.md``.

Why this exists
---------------
A 2026-09-24 review found ``reports/`` holding 325 tracked files behind a three-line README, ``scripts/``
(81 files) and ``docs/`` (120) with no index at all, and no way to tell which study a report belongs to.
Frozen evidence cannot be moved into per-study folders -- its paths are pinned -- so the indexes carry the
organisation instead: every tracked file or directory is listed with its kind and study.

The indexes are views of the tree, not places that own anything. They are deterministic (no dates, sorted
input), so ``tests/results/test_generated_indexes.py`` regenerates them and requires a byte-identical match.
A new ``reports/`` subdirectory must be added to ``REPORT_DIRECTORIES`` below, or generation fails -- that is
what keeps the study column complete.

Usage:
    python scripts/reporting/generate_indexes.py            # write the three indexes
    python scripts/reporting/generate_indexes.py --check    # fail if any is stale
"""

from __future__ import annotations

import argparse
import ast
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = "<!-- Generated by scripts/reporting/generate_indexes.py. Do not edit by hand; run it. -->\n"

#: Every tracked subdirectory of reports/, its study and what it holds.
REPORT_DIRECTORIES: dict[str, tuple[str, str]] = {
    "audits": ("Study 001", "The Study 001 claim audit: findings, resolutions and the audit's own record"),
    "baselines": ("Study 001", "B0 baseline predictions and metrics"),
    "canonical-v3": ("Study 002", "canonical-v3 (workstream C1): manifest, balance, provenance gate"),
    "comparisons": ("Study 001", "Stage-to-stage comparison records"),
    "data": ("Study 001", "Corpus, freeze, readiness and ablation records (JSON)"),
    "evaluation": ("Study 001", "Evaluation manifests of the frozen held-out partitions"),
    "experiments": ("Study 001", "Experiment-level records"),
    "failures": ("Study 001", "Failure clustering"),
    "hardware": ("Study 001", "GPU smoke records"),
    "incidents": ("Study 001", "Incident records (see docs/INCIDENT_LOG.md)"),
    "normalization-v3": ("Study 002", "normalization-v3: builds, verification, audits, re-anchoring"),
    "optimization": ("Study 001", "Optimization producer records"),
    "pdet": ("Study 002", "P-DET-v1: the frozen population, annotation exports, review queue, model-label provenance"),
    "pdet-coverage": ("Study 002", "P-DET-COVERAGE-v1 (and its routing task): population, three-model labels, reference, audit trails"),
    "pdet-coverage-v2": ("Study 002", "P-DET-COVERAGE-v2: population, three-model labels, reference, audit trails"),
    "prose-classifier": ("Study 002", "Decision-classifier development sets, check rounds and one-shot tests; see its README"),
    "releases": ("Study 001", "Hugging Face publication records"),
    "source-screening": ("Study 002", "Data-source screenings: the written report and the artifacts behind its numbers"),
    "study-002": ("Study 002", "New Study 002 evidence: the ANSWER strata candidate population and its three-model labels"),
    "training": ("Study 001", "Pre-training component-gate evidence"),
    "visual": ("Study 001", "Figures"),
}

KIND_RULES = (
    ("ERRATA", "errata"),
    ("PLAN", "plan"),
    ("DESIGN", "plan"),
    ("DECISION", "decision"),
    ("CLOSURE", "closure"),
    ("SUMMARY", "closure"),
    ("AUDIT", "audit"),
    ("FORENSICS", "audit"),
    ("EVALUATION", "evaluation"),
    ("PARITY", "evaluation"),
    ("REGRESSION", "evaluation"),
    ("EXECUTION", "execution"),
    ("RUN", "execution"),
    ("READINESS", "readiness"),
    ("HANDOFF", "handoff"),
    ("STATUS", "status"),
)


def tracked(prefix: str) -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "-z", "--", prefix], cwd=ROOT, capture_output=True, check=True
    ).stdout.decode()
    return sorted(name for name in out.split("\0") if name)


def first_heading(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("#"):
            return line.lstrip("#").strip()
    return "(no heading)"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").strip()


def kind_of(name: str) -> str:
    upper = name.upper()
    return next((kind for token, kind in KIND_RULES if token in upper), "report")


def build_reports() -> str:
    files = tracked("reports")
    flat = [f for f in files if f.count("/") == 1 and f.endswith(".md") and f != "reports/README.md"]
    counts = Counter(f.split("/")[1] for f in files if f.count("/") >= 2)
    unknown = sorted(set(counts) - set(REPORT_DIRECTORIES))
    if unknown:
        raise SystemExit(f"reports/ has unindexed directories {unknown}; add them to REPORT_DIRECTORIES")
    lines = [
        HEADER,
        "# Reports",
        "",
        "Written analyses and the evidence behind them. **Study 001** files are frozen at tag `study-001`",
        "and are corrected only in [`ERRATA.md`](ERRATA.md), never in place. **Study 002** evidence sits in",
        "the directories marked below; its text is in [`docs/research/study-002/`](../docs/research/study-002/README.md).",
        "Terms: [glossary](../docs/GLOSSARY.md).",
        "",
        "## Written reports",
        "",
        "| Report | Kind | Study | Title |",
        "|---|---|---|---|",
    ]
    for f in flat:
        name = f.split("/", 1)[1]
        study = "all" if name == "ERRATA.md" else "Study 001"
        title = _cell(first_heading(ROOT / f))
        lines.append(f"| [`{name}`]({name}) | {kind_of(name)} | {study} | {title} |")
    lines += ["", "## Evidence directories", "", "| Directory | Files | Study | Holds |", "|---|---:|---|---|"]
    for directory in sorted(counts):
        study, holds = REPORT_DIRECTORIES[directory]
        lines.append(f"| [`{directory}/`]({directory}/) | {counts[directory]} | {study} | {_cell(holds)} |")
    lines += ["", f"{len(files)} tracked files in total.", ""]
    return "\n".join(lines)


def docstring_line(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    if path.suffix == ".py":
        try:
            doc = ast.get_docstring(ast.parse(text))
        except SyntaxError:
            doc = None
        if doc:
            return doc.strip().splitlines()[0]
    for line in text.splitlines()[1:12]:
        stripped = line.strip()
        if stripped.startswith("#") and len(stripped) > 2:
            return stripped.lstrip("#").strip()
    return "(no description)"


def build_scripts() -> str:
    files = [f for f in tracked("scripts") if f.endswith((".py", ".sh")) and not f.endswith("__init__.py")]
    lines = [
        HEADER,
        "# Scripts",
        "",
        "Campaign, audit, freeze and reporting tooling, run by hand or by CI. Reusable logic belongs in",
        "`src/opengrad/`; a script should parse arguments, call the package and write its artifact. Each row is",
        "the script's own first docstring line.",
        "",
    ]
    groups: dict[str, list[str]] = {}
    for f in files:
        parts = f.split("/")
        group = parts[1] if len(parts) > 2 else "(top level)"
        groups.setdefault(group, []).append(f)
    for group in sorted(groups, key=lambda g: (g != "(top level)", g)):
        lines += [f"## {group}", "", "| Script | Purpose |", "|---|---|"]
        for f in groups[group]:
            rel = f.split("/", 1)[1]
            lines.append(f"| [`{rel}`]({rel}) | {_cell(docstring_line(ROOT / f))} |")
        lines.append("")
    lines += [f"{len(files)} scripts.", ""]
    return "\n".join(lines)


def build_docs() -> str:
    files = [f for f in tracked("docs") if f.endswith(".md") and f != "docs/README.md"]
    lines = [
        HEADER,
        "# Documentation",
        "",
        "Living specifications and methodology. Start with the [glossary](GLOSSARY.md), the",
        "[repository layout](architecture/repository.md) and the [studies](research/STUDIES.md). Study 002's",
        "current state is in [`research/study-002/README.md`](research/study-002/README.md#current-state).",
        "",
    ]
    groups: dict[str, list[str]] = {}
    for f in files:
        rel = f.split("/", 1)[1]
        group = rel.rsplit("/", 1)[0] if "/" in rel else "(top level)"
        groups.setdefault(group, []).append(rel)
    for group in sorted(groups, key=lambda g: (g != "(top level)", g)):
        lines += [f"## {group}", "", "| Document | Title |", "|---|---|"]
        for rel in groups[group]:
            lines.append(f"| [`{rel}`]({rel}) | {_cell(first_heading(ROOT / 'docs' / rel))} |")
        lines.append("")
    lines += [f"{len(files)} documents.", ""]
    return "\n".join(lines)


OUTPUTS = {
    "reports/README.md": build_reports,
    "scripts/README.md": build_scripts,
    "docs/README.md": build_docs,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if an index is stale")
    args = parser.parse_args(argv)
    stale = []
    for relative, build in OUTPUTS.items():
        text = build()
        path = ROOT / relative
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != text:
                stale.append(relative)
            continue
        with path.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print(f"wrote {relative}")
    for relative in stale:
        print(f"STALE: {relative}; run: python scripts/reporting/generate_indexes.py", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
