#!/usr/bin/env python3
"""Generate the data-source views: ``docs/datasets/SOURCE_REGISTRY.md`` and ``SOURCE_SCREENING.md``.

Why this exists
---------------
Pinned revisions, licences and redistribution outcomes used to be retyped into several documents
by hand, and a count in prose ("eighteen candidates hold none") is a number nobody regenerates.
This script derives both views from the two registries -- ``registry/datasets.yaml`` (adopted
sources and derived corpora) and ``registry/source_screening.yaml`` (every candidate screened,
with a verdict per criterion) -- so the documents are views of state rather than places that own
it. Output is deterministic; ``tests/registry/test_source_views.py`` requires a byte-identical
match.

The screening view follows the reporting logic of a PRISMA flow: how many candidates were
identified, how many were excluded and on which criterion, how many are on the watch list, and how
many were shortlisted. An exclusion is counted under every criterion that decides it, so the
per-criterion counts can sum to more than the exclusions.

Usage:
    python scripts/reporting/generate_source_views.py            # write both documents
    python scripts/reporting/generate_source_views.py --check    # fail if either is stale
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
REGISTRY_VIEW = "docs/datasets/SOURCE_REGISTRY.md"
SCREENING_VIEW = "docs/datasets/SOURCE_SCREENING.md"
HEADER = (
    "<!-- Generated by scripts/reporting/generate_source_views.py from {sources}. "
    "Do not edit; regenerate. -->\n"
)


def _load(name: str) -> dict[str, Any]:
    return yaml.safe_load((ROOT / name).read_text(encoding="utf-8")) or {}


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ") if value not in (None, "") else "—"


def _short(value: object) -> str:
    text = str(value or "")
    return f"`{text[:12]}`" if text else "—"


def build_registry_view() -> str:
    records = _load("registry/datasets.yaml").get("datasets", [])
    lines = [
        HEADER.format(sources="registry/datasets.yaml"),
        "# Registered data sources",
        "",
        "Adopted upstream sources and the corpora OpenGrad derived from them, as recorded in",
        "`registry/datasets.yaml` (record schema `registry/dataset_record.schema.json`). The procedure for",
        "adding one is [ADDING_A_SOURCE.md](ADDING_A_SOURCE.md).",
        "",
        "| Id | Role | Lifecycle | Licence | Redistribution | Revision | Files pinned | SFT splits | Contamination |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for record in records:
        stages = [str(s) for s in record.get("intended_stages") or []]
        trains = any(s.removeprefix("future_") == "sft" for s in stages)
        splits = ", ".join(record.get("allowed_splits") or []) or ("train" if trains else "—")
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{record['id']}`",
                    _cell(record.get("role")),
                    _cell(record.get("lifecycle")),
                    _cell((record.get("license") or {}).get("value")),
                    _cell(record.get("redistribution")),
                    _short((record.get("source_revision") or {}).get("value")),
                    str(len(record.get("distribution") or [])),
                    splits if trains else "— (not an SFT source)",
                    _cell(record.get("contamination_status")),
                ]
            )
            + " |"
        )
    counts = Counter(str(r.get("role")) for r in records)
    lines += [
        "",
        f"{len(records)} records: "
        + ", ".join(f"{count} {role}" for role, count in sorted(counts.items()))
        + ".",
        "",
    ]
    return "\n".join(lines)


def _flow(screening: dict[str, Any]) -> list[str]:
    candidates = screening.get("candidates") or []
    decisions = Counter(str(c.get("decision")) for c in candidates)
    kinds = Counter(str(c.get("kind")) for c in candidates)
    names = {str(c["id"]): str(c["name"]) for c in screening.get("criteria") or []}
    decisive = Counter(
        criterion
        for c in candidates
        if c.get("decision") == "EXCLUDED"
        for criterion in c.get("decisive_criteria") or []
    )
    zero = sum(
        1 for c in candidates if (c.get("answer_items") or {}).get("basis") == "BY_DESIGN_ZERO"
    )
    lines = [
        "| Stage | Count |",
        "|---|---|",
        (
            f"| Candidates identified | {len(candidates)} ({kinds.get('ITEM_SOURCE', 0)} item sources, "
            f"{kinds.get('QUESTION_SOURCE', 0)} question sources) |"
        ),
        f"| Excluded | {decisions.get('EXCLUDED', 0)} |",
    ]
    for criterion, count in sorted(decisive.items()):
        lines.append(f"| … on {criterion} `{names.get(criterion, '?')}` | {count} |")
    lines += [
        f"| Watch list | {decisions.get('WATCHLIST', 0)} |",
        f"| Shortlisted | {decisions.get('SHORTLISTED', 0)} |",
        "",
        f"{zero} candidates hold zero qualifying items by design.",
    ]
    return lines


def build_screening_view() -> str:
    registry = _load("registry/source_screening.yaml")
    lines = [
        HEADER.format(sources="registry/source_screening.yaml"),
        "# Source screenings",
        "",
        "Every candidate considered for a purpose, including the rejected ones, with a verdict per",
        "criterion (`registry/source_screening.yaml`, schema `registry/source_screening.schema.json`).",
        "Verdicts: PASS, PARTIAL, FAIL, UNKNOWN, n/a.",
        "",
    ]
    for screening in registry.get("screenings") or []:
        criteria = [str(c["id"]) for c in screening.get("criteria") or []]
        decision = screening.get("owner_decision") or {}
        lines += [
            f"## `{screening['id']}`",
            "",
            _cell(screening.get("question")),
            "",
            f"- Purpose: {screening.get('purpose')}; requirement: `{screening.get('requirement_source')}`",
            f"- Owner decision: **{decision.get('status')}**"
            + (
                f" — adopted {', '.join(decision.get('adopted') or [])}"
                if decision.get("adopted")
                else ""
            ),
            f"- Report: `{(screening.get('search') or {}).get('report')}`",
            "",
            "### Criteria",
            "",
        ]
        lines += [
            f"- **{c['id']}** `{c['name']}` — {_cell(c['test'])}" for c in screening["criteria"]
        ]
        lines += ["", "### Flow", "", *_flow(screening), "", "### Candidates", ""]
        header = ["Candidate", "Kind", "Licence", *criteria, "Decision"]
        lines += ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
        symbol = {
            "PASS": "PASS",
            "PARTIAL": "PARTIAL",
            "FAIL": "**FAIL**",
            "UNKNOWN": "?",
            "NOT_APPLICABLE": "n/a",
        }
        order = {"SHORTLISTED": 0, "WATCHLIST": 1, "EXCLUDED": 2}
        for candidate in sorted(
            screening.get("candidates") or [],
            key=lambda c: (order.get(c.get("decision"), 3), c["id"]),
        ):
            verdicts = candidate.get("verdicts") or {}
            cells = [
                f"`{candidate['id']}`",
                "item" if candidate.get("kind") == "ITEM_SOURCE" else "question",
                _cell((candidate.get("license") or {}).get("value")),
                *[symbol.get((verdicts.get(c) or {}).get("result"), "—") for c in criteria],
                _cell(candidate.get("decision")),
            ]
            lines.append("| " + " | ".join(cells) + " |")
        lines.append("")
    return "\n".join(lines)


def render() -> dict[str, str]:
    return {REGISTRY_VIEW: build_registry_view(), SCREENING_VIEW: build_screening_view()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="fail if a view is stale")
    args = parser.parse_args()
    stale = []
    for name, text in render().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {name}")
    if stale:
        print("stale: " + ", ".join(stale))
        return 1
    if args.check:
        print("CURRENT")
    return 0


if __name__ == "__main__":
    sys.exit(main())
