"""Durable, human-authored Level-5 contamination adjudication and quarantine.

Level 5 of the benchmark contamination policy is a *human* judgment. This module owns the
artifact that records those judgments and the quarantine list that excludes adjudicated
examples from evaluation.

Design rules:

* ``reports/data/behavioral-heldout-v2-contamination.json`` is machine-generated by
  :mod:`opengrad.contamination.heldout`. It is an *input* to adjudication and is never the
  place a human writes a verdict.
* The human verdicts live in ``reports/data/behavioral-heldout-v2-contamination-audit.json``.
  The scanner must never write this file; only :func:`sync_audit` and :func:`apply_verdict`
  do, and both preserve every existing judgment.
* A verdict is only trusted while the evidence it was made against is unchanged. Each item
  records a ``finding_fingerprint``, and the artifact records benchmark and training-corpus
  fingerprints. If any of those move, the affected judgments are stale and the gate blocks.
* A ``CONTAMINATED`` verdict must be accompanied by quarantine before the gate can pass.
"""

from __future__ import annotations

import getpass
import hashlib
import json
import os
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

MANIFEST_ID = "behavioral-heldout-v2"

VERDICT_PENDING = "PENDING"
VERDICT_CONTAMINATED = "CONTAMINATED"
VERDICT_INCIDENTAL = "INCIDENTAL_OVERLAP"
VERDICT_VALUES = (VERDICT_PENDING, VERDICT_CONTAMINATED, VERDICT_INCIDENTAL)
RESOLVED_VERDICTS = frozenset({VERDICT_CONTAMINATED, VERDICT_INCIDENTAL})

AUDIT_PATH = Path("reports/data/behavioral-heldout-v2-contamination-audit.json")
QUARANTINE_PATH = Path("reports/evaluation/behavioral-heldout-v2-quarantine.json")
BENCHMARK_MANIFEST = Path("reports/evaluation/behavioral-heldout-v2.manifest.json")


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _canonical(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def default_reviewer() -> str:
    return (
        os.environ.get("OPENGRAD_REVIEWER")
        or os.environ.get("USER")
        or getpass.getuser()
        or "UNKNOWN_REVIEWER"
    )


def validate_verdict(verdict: str) -> str:
    """Reject anything that is not an exact supported verdict."""
    if not isinstance(verdict, str) or verdict not in VERDICT_VALUES:
        raise ValueError(f"verdict must be one of {', '.join(VERDICT_VALUES)} (got {verdict!r})")
    return verdict


# --------------------------------------------------------------------------------------
# Fingerprints
# --------------------------------------------------------------------------------------


def benchmark_fingerprint(root: Path) -> str | None:
    """Identity of the frozen held-out benchmark contract (splits, counts, content hashes)."""
    path = root / BENCHMARK_MANIFEST
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    splits = manifest.get("splits")
    if not isinstance(splits, list):
        return None
    identity = [
        {
            "id": split.get("id"),
            "items": split.get("items"),
            "content_hash": split.get("content_hash"),
        }
        for split in splits
        if isinstance(split, dict)
    ]
    identity.sort(key=lambda item: str(item["id"]))
    return _sha256_text(
        _canonical({"manifest_id": manifest.get("manifest_id"), "splits": identity})
    )


def training_corpus_fingerprint(root: Path, release_dir: Path | None = None) -> str | None:
    """Identity of the built canonical training corpus, cheap enough to recompute."""
    base = (root / (release_dir or Path(".release/hf/toolpolicy-canonical-v1"))).resolve()
    manifest_path = base / "release-manifest.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    shards = manifest.get("output_shards")
    if not isinstance(shards, list):
        return None
    identity = sorted(
        (str(shard.get("file")), str(shard.get("sha256")))
        for shard in shards
        if isinstance(shard, dict)
    )
    return _sha256_text(
        _canonical({"record_count": manifest.get("record_count"), "shards": identity})
    )


def finding_fingerprint(entry: dict[str, Any]) -> str:
    """Identity of one held-out finding: its id, levels, and matched training records."""
    raw_matches = entry.get("matches")
    matches: list[Any] = raw_matches if isinstance(raw_matches, list) else []
    canonical_matches = sorted(
        (
            str(match.get("level")),
            _canonical(match.get("training"))
            if isinstance(match.get("training"), list)
            else str(match.get("training")),
        )
        for match in matches
        if isinstance(match, dict)
    )
    return _sha256_text(
        _canonical(
            {
                "heldout": entry.get("heldout"),
                "levels": sorted(str(level) for level in entry.get("levels", [])),
                "matches": canonical_matches,
            }
        )
    )


# --------------------------------------------------------------------------------------
# Artifact data model
# --------------------------------------------------------------------------------------


@dataclass
class AuditItem:
    record_id: str
    heldout_text: str = ""
    split: str = ""
    expected_decision: str | None = None
    candidates: dict[str, Any] = field(default_factory=dict)
    tools: list[str] = field(default_factory=list)
    match_levels: list[str] = field(default_factory=list)
    matches: list[dict[str, Any]] = field(default_factory=list)
    training_evidence: list[dict[str, Any]] = field(default_factory=list)
    finding_fingerprint: str = ""
    verdict: str = VERDICT_PENDING
    reason: str = ""
    reviewer: str = ""
    review_date: str = ""
    stale: bool = False
    stale_reason: str = ""

    def resolved(self) -> bool:
        return self.verdict in RESOLVED_VERDICTS and not self.stale

    def to_dict(self) -> dict[str, Any]:
        return {
            "record_id": self.record_id,
            "split": self.split,
            "heldout_text": self.heldout_text,
            "expected_decision": self.expected_decision,
            "candidates": self.candidates,
            "tools": self.tools,
            "match_levels": sorted(self.match_levels),
            "finding_fingerprint": self.finding_fingerprint,
            "verdict": self.verdict,
            "reason": self.reason,
            "reviewer": self.reviewer,
            "review_date": self.review_date,
            "stale": self.stale,
            "stale_reason": self.stale_reason,
            "matches": self.matches,
            "training_evidence": self.training_evidence,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AuditItem:
        verdict = data.get("verdict", VERDICT_PENDING)
        try:
            validate_verdict(verdict)
        except ValueError:
            # A malformed stored verdict must not be silently coerced into a passing
            # value; surface it as PENDING so the gate blocks and the reviewer sees it.
            verdict = VERDICT_PENDING
        candidates = data.get("candidates")
        tools = data.get("tools")
        return cls(
            record_id=str(data.get("record_id", "")),
            heldout_text=str(data.get("heldout_text", "")),
            split=str(data.get("split", "")),
            expected_decision=data.get("expected_decision"),
            candidates=dict(candidates) if isinstance(candidates, dict) else {},
            tools=[str(value) for value in tools] if isinstance(tools, list) else [],
            match_levels=[str(v) for v in data.get("match_levels", [])],
            matches=list(data.get("matches", [])),
            training_evidence=list(data.get("training_evidence", [])),
            finding_fingerprint=str(data.get("finding_fingerprint", "")),
            verdict=verdict,
            reason=str(data.get("reason", "")),
            reviewer=str(data.get("reviewer", "")),
            review_date=str(data.get("review_date", "")),
            stale=bool(data.get("stale", False)),
            stale_reason=str(data.get("stale_reason", "")),
        )


@dataclass
class AuditArtifact:
    schema_version: int = 1
    manifest_id: str = MANIFEST_ID
    benchmark_fingerprint: str | None = None
    training_corpus_fingerprint: str | None = None
    created_at: str = ""
    updated_at: str = ""
    items: list[AuditItem] = field(default_factory=list)

    def by_id(self) -> dict[str, AuditItem]:
        return {item.record_id: item for item in self.items}

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "manifest_id": self.manifest_id,
            "artifact_kind": "HUMAN_LEVEL_5_ADJUDICATION",
            "note": (
                "Human-authored Level-5 verdicts. Machine-generated contamination reports "
                "must never be edited by hand, and this file must never be written by the "
                "scanner; use `opengrad-contamination adjudicate`."
            ),
            "benchmark_fingerprint": self.benchmark_fingerprint,
            "training_corpus_fingerprint": self.training_corpus_fingerprint,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "items": [item.to_dict() for item in sorted(self.items, key=lambda i: i.record_id)],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AuditArtifact:
        items = data.get("items")
        return cls(
            schema_version=int(data.get("schema_version", 1)),
            manifest_id=str(data.get("manifest_id", MANIFEST_ID)),
            benchmark_fingerprint=data.get("benchmark_fingerprint"),
            training_corpus_fingerprint=data.get("training_corpus_fingerprint"),
            created_at=str(data.get("created_at", "")),
            updated_at=str(data.get("updated_at", "")),
            items=[AuditItem.from_dict(item) for item in items] if isinstance(items, list) else [],
        )


def load_audit(path: Path) -> AuditArtifact | None:
    """Load the audit artifact, or None when it does not exist yet."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    return AuditArtifact.from_dict(data)


def save_audit(path: Path, artifact: AuditArtifact) -> Path:
    """Write the audit artifact deterministically (stable order, stable formatting)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(artifact.to_dict(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(payload, encoding="utf-8")
    os.replace(temporary, path)
    return path


# --------------------------------------------------------------------------------------
# Quarantine
# --------------------------------------------------------------------------------------


@dataclass
class Quarantine:
    schema_version: int = 1
    manifest_id: str = MANIFEST_ID
    generated_from_audit: str = str(AUDIT_PATH)
    updated_at: str = ""
    excluded: list[dict[str, Any]] = field(default_factory=list)

    def record_ids(self) -> set[str]:
        return {str(entry.get("record_id")) for entry in self.excluded if entry.get("record_id")}

    def by_split(self) -> dict[str, set[str]]:
        result: dict[str, set[str]] = {}
        for entry in self.excluded:
            split = str(entry.get("split") or "")
            example_id = str(entry.get("example_id") or "")
            if split and example_id:
                result.setdefault(split, set()).add(example_id)
        return result

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "manifest_id": self.manifest_id,
            "artifact_kind": "HELDOUT_QUARANTINE",
            "note": (
                "Held-out evaluation examples excluded from B0 and all subsequent held-out "
                "evaluations after a CONTAMINATED Level-5 verdict. Regenerate with "
                "`opengrad-contamination quarantine --apply`."
            ),
            "generated_from_audit": self.generated_from_audit,
            "updated_at": self.updated_at,
            "excluded": sorted(self.excluded, key=lambda entry: str(entry.get("record_id"))),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Quarantine:
        excluded = data.get("excluded")
        return cls(
            schema_version=int(data.get("schema_version", 1)),
            manifest_id=str(data.get("manifest_id", MANIFEST_ID)),
            generated_from_audit=str(data.get("generated_from_audit", AUDIT_PATH)),
            updated_at=str(data.get("updated_at", "")),
            excluded=list(excluded) if isinstance(excluded, list) else [],
        )


def load_quarantine(path: Path) -> Quarantine:
    """Load the quarantine list; a missing file means nothing is excluded."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return Quarantine()
    if not isinstance(data, dict):
        return Quarantine()
    return Quarantine.from_dict(data)


def build_quarantine(audit: AuditArtifact, *, now: str | None = None) -> Quarantine:
    """Derive the quarantine list from CONTAMINATED verdicts."""
    entries = [
        {
            "record_id": item.record_id,
            "split": item.split,
            "example_id": item.record_id.split(":", 1)[-1],
            "verdict": item.verdict,
            "reason": item.reason,
            "reviewer": item.reviewer,
            "review_date": item.review_date,
        }
        for item in audit.items
        if item.verdict == VERDICT_CONTAMINATED
    ]
    return Quarantine(updated_at=now or _now(), excluded=entries)


def save_quarantine(path: Path, quarantine: Quarantine) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(quarantine.to_dict(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(payload, encoding="utf-8")
    os.replace(temporary, path)
    return path


# --------------------------------------------------------------------------------------
# Synchronisation and adjudication
# --------------------------------------------------------------------------------------


def _entry_to_item(entry: dict[str, Any]) -> AuditItem:
    candidates = entry.get("candidates")
    tools = entry.get("tools")
    recorded = entry.get("finding_fingerprint")
    return AuditItem(
        record_id=str(entry.get("heldout")),
        heldout_text=str(entry.get("text", "")),
        split=str(entry.get("split", "")),
        expected_decision=entry.get("expected_decision"),
        candidates=dict(candidates) if isinstance(candidates, dict) else {},
        tools=[str(value) for value in tools] if isinstance(tools, list) else [],
        match_levels=[str(level) for level in entry.get("levels", [])],
        matches=list(entry.get("matches", [])),
        training_evidence=list(entry.get("training_evidence", [])),
        # Recompute rather than trust the report's copy, so an absent or altered
        # fingerprint in the generated report cannot desynchronise the audit.
        finding_fingerprint=finding_fingerprint(entry) if not recorded else str(recorded),
    )


def sync_audit(
    report: dict[str, Any],
    *,
    existing: AuditArtifact | None = None,
    benchmark_fp: str | None = None,
    training_fp: str | None = None,
    quarantined_ids: set[str] | None = None,
    now: str | None = None,
) -> AuditArtifact:
    """Reconcile the audit artifact with the current scanner findings.

    Existing judgments are preserved verbatim. New findings are added as ``PENDING``. An
    item whose finding changed, or any item at all when the benchmark or training corpus
    fingerprint moved, is flagged stale so it cannot pass the gate until re-adjudicated.

    Findings that were quarantined disappear from the scanner queue (they are no longer
    part of the benchmark); their adjudication is carried forward rather than erased, since
    the judgment is the reason the example is excluded.
    """
    timestamp = now or _now()
    queue = report.get("audit_queue")
    if not isinstance(queue, list):
        raise TypeError("scanner report has no audit_queue")
    excluded = quarantined_ids or set()

    previous = existing or AuditArtifact(created_at=timestamp)
    previous_items = previous.by_id()
    if previous.benchmark_fingerprint is not None:
        global_changed = (
            previous.benchmark_fingerprint != benchmark_fp
            or previous.training_corpus_fingerprint != training_fp
        )
    else:
        global_changed = False

    items: list[AuditItem] = []
    seen: set[str] = set()
    for entry in queue:
        if not isinstance(entry, dict):
            continue
        fresh = _entry_to_item(entry)
        seen.add(fresh.record_id)
        old = previous_items.get(fresh.record_id)
        if old is None:
            items.append(fresh)
            continue
        # Carry the human judgment forward; refresh the machine evidence.
        fresh.verdict = old.verdict
        fresh.reason = old.reason
        fresh.reviewer = old.reviewer
        fresh.review_date = old.review_date
        if global_changed:
            fresh.stale = True
            fresh.stale_reason = "benchmark or training corpus fingerprint changed"
        elif old.finding_fingerprint != fresh.finding_fingerprint:
            fresh.stale = True
            fresh.stale_reason = "scanner finding changed since this verdict was recorded"
        items.append(fresh)

    # Keep adjudications for quarantined examples even though they left the queue.
    for record_id, old in previous_items.items():
        if record_id in seen or record_id not in excluded:
            continue
        items.append(old)

    return AuditArtifact(
        schema_version=previous.schema_version,
        manifest_id=MANIFEST_ID,
        benchmark_fingerprint=benchmark_fp,
        training_corpus_fingerprint=training_fp,
        created_at=previous.created_at or timestamp,
        updated_at=timestamp,
        items=items,
    )


def apply_verdict(
    artifact: AuditArtifact,
    record_id: str,
    verdict: str,
    *,
    reason: str = "",
    reviewer: str = "",
    now: str | None = None,
) -> AuditItem:
    """Record one human verdict, validating it and clearing any stale flag."""
    validate_verdict(verdict)
    target = artifact.by_id().get(record_id)
    if target is None:
        raise KeyError(f"no adjudication item for {record_id}")
    target.verdict = verdict
    target.reason = reason
    target.reviewer = reviewer or default_reviewer()
    target.review_date = now or _now()
    target.stale = False
    target.stale_reason = ""
    artifact.updated_at = target.review_date
    return target


# --------------------------------------------------------------------------------------
# Evaluation
# --------------------------------------------------------------------------------------


@dataclass
class AuditEvaluation:
    complete: bool
    level_5: str
    effective_status: str
    total: int
    resolved: int
    pending: int
    contaminated: int
    incidental: int
    quarantined: int
    stale: int
    problems: list[str] = field(default_factory=list)

    def detail(self) -> str:
        parts = [
            f"findings={self.total}",
            f"resolved={self.resolved}",
            f"pending={self.pending}",
            f"quarantined={self.quarantined}",
        ]
        if self.stale:
            parts.append(f"stale={self.stale}")
        if self.problems:
            parts.append("problems=" + "; ".join(self.problems))
        return "; ".join(parts)


def evaluate_audit(
    report: dict[str, Any] | None,
    audit: AuditArtifact | None,
    quarantine: Quarantine,
    *,
    benchmark_fp: str | None,
    training_fp: str | None,
) -> AuditEvaluation:
    """Decide whether Level 5 is complete and whether contamination blocks readiness."""
    if not report or not isinstance(report.get("audit_queue"), list):
        return AuditEvaluation(
            complete=False,
            level_5="NOT_RUN",
            effective_status="REVIEW_REQUIRED_LEVEL_5_PENDING",
            total=0,
            resolved=0,
            pending=0,
            contaminated=0,
            incidental=0,
            quarantined=len(quarantine.record_ids()),
            stale=0,
            problems=["scanner findings are unavailable"],
        )

    findings = [entry for entry in report["audit_queue"] if isinstance(entry, dict)]
    quarantined_ids = quarantine.record_ids()
    total = len(findings)
    problems: list[str] = []

    if audit is None:
        if total == 0 and not quarantined_ids:
            # Nothing was flagged, so there is nothing for a human to adjudicate.
            return AuditEvaluation(
                complete=True,
                level_5="COMPLETE",
                effective_status="CLEAN",
                total=0,
                resolved=0,
                pending=0,
                contaminated=0,
                incidental=0,
                quarantined=0,
                stale=0,
                problems=[],
            )
        blocked_problems: list[str] = []
        if total:
            blocked_problems.append(f"{total} finding(s) have no human adjudication artifact")
        if quarantined_ids:
            blocked_problems.append("a quarantine list exists without an audit artifact")
        return AuditEvaluation(
            complete=False,
            level_5="NOT_RUN",
            effective_status="REVIEW_REQUIRED_LEVEL_5_PENDING",
            total=total,
            resolved=0,
            pending=total,
            contaminated=0,
            incidental=0,
            quarantined=len(quarantined_ids),
            stale=0,
            problems=blocked_problems,
        )

    # A changed benchmark or training corpus invalidates every stored judgment.
    if audit.benchmark_fingerprint != benchmark_fp:
        problems.append("benchmark fingerprint changed since adjudication")
    if audit.training_corpus_fingerprint != training_fp:
        problems.append("training corpus fingerprint changed since adjudication")

    items = audit.by_id()
    present = {str(entry.get("heldout")) for entry in findings}
    resolved = pending = contaminated = incidental = stale = 0
    missing: list[str] = []

    for entry in findings:
        record_id = str(entry.get("heldout"))
        item = items.get(record_id)
        if item is None:
            missing.append(record_id)
            pending += 1
            continue
        if item.stale:
            stale += 1
            pending += 1
            continue
        if item.finding_fingerprint != finding_fingerprint(entry):
            stale += 1
            pending += 1
            continue
        if item.verdict == VERDICT_PENDING:
            pending += 1
            continue
        resolved += 1
        if item.verdict == VERDICT_CONTAMINATED:
            contaminated += 1
        else:
            incidental += 1

    if missing:
        problems.append(f"{len(missing)} finding(s) absent from the audit artifact")

    # Every CONTAMINATED verdict must be demonstrably excluded from evaluation.
    quarantined = 0
    unquarantined: list[str] = []
    for item in audit.items:
        if item.verdict != VERDICT_CONTAMINATED:
            continue
        if item.record_id in quarantined_ids:
            quarantined += 1
        else:
            unquarantined.append(item.record_id)
    if unquarantined:
        problems.append(
            "CONTAMINATED finding(s) not quarantined: " + ", ".join(sorted(unquarantined))
        )

    # Audit entries for findings that no longer exist are stale bookkeeping.
    orphaned = sorted(set(items) - present - quarantined_ids)
    if orphaned:
        problems.append(f"{len(orphaned)} audit entr(ies) no longer match a finding")

    complete = not problems and pending == 0
    if complete:
        level_5 = "COMPLETE"
        # Quarantining a contaminated example is a resolved review, not a clean corpus:
        # report SEMANTIC_REVIEW_COMPLETE whenever anything was ever excluded.
        effective_status = (
            "CLEAN" if total == 0 and not quarantined_ids else "SEMANTIC_REVIEW_COMPLETE"
        )
    else:
        level_5 = "NOT_RUN"
        effective_status = "REVIEW_REQUIRED_LEVEL_5_PENDING"

    return AuditEvaluation(
        complete=complete,
        level_5=level_5,
        effective_status=effective_status,
        total=total,
        resolved=resolved,
        pending=pending,
        contaminated=contaminated,
        incidental=incidental,
        quarantined=quarantined,
        stale=stale,
        problems=problems,
    )
